-- Content Generation & Publishing Automation
-- Initial schema migration
-- Author: Oluwademilade Bickersteth
-- Date: 2026-03-25

-- ============================================
-- SUBMISSIONS TABLE
-- Stores content ideas and their generated drafts
-- ============================================
CREATE TABLE IF NOT EXISTS submissions (
  id TEXT PRIMARY KEY,  -- format: sub_xxx (generated by n8n)
  content_hash TEXT NOT NULL,  -- for duplicate detection
  input_type TEXT NOT NULL CHECK (input_type IN ('url', 'raw_idea')),
  raw_input TEXT NOT NULL,  -- original user input (idea text or URL)
  content_base TEXT,  -- extracted/cleaned content used for generation

  -- Draft storage (JSONB array of 3 draft objects)
  drafts JSONB DEFAULT '[]'::jsonb,
  -- Each draft: {index, angle, title, content, wordCount}

  selected_draft INTEGER CHECK (selected_draft BETWEEN 1 AND 3),

  -- Status machine: generating → pending_review → processing → published|scheduled|error
  status TEXT NOT NULL DEFAULT 'generating'
    CHECK (status IN ('generating', 'pending_review', 'processing', 'published', 'scheduled', 'error')),
  error_details TEXT,

  publish_immediately BOOLEAN DEFAULT false,

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for duplicate detection (hash + recent time window)
CREATE INDEX idx_submissions_hash_created ON submissions (content_hash, created_at DESC);

-- Index for status-based queries (frontend listing)
CREATE INDEX idx_submissions_status ON submissions (status);

-- Index for ordering by creation date
CREATE INDEX idx_submissions_created ON submissions (created_at DESC);

-- ============================================
-- ADAPTED CONTENT TABLE
-- Stores platform-specific adaptations of selected drafts
-- ============================================
CREATE TABLE IF NOT EXISTS adapted_content (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id TEXT NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,

  -- LinkedIn adaptation
  linkedin_content TEXT,
  linkedin_char_count INTEGER,
  linkedin_has_cta BOOLEAN DEFAULT false,
  linkedin_published_at TIMESTAMPTZ,
  linkedin_published_url TEXT,

  -- X/Twitter adaptation
  twitter_content TEXT,
  twitter_char_count INTEGER CHECK (twitter_char_count <= 280),
  twitter_truncated BOOLEAN DEFAULT false,
  twitter_published_at TIMESTAMPTZ,
  twitter_published_url TEXT,

  -- Email newsletter adaptation
  newsletter_subject TEXT,
  newsletter_content TEXT,
  newsletter_word_count INTEGER,
  newsletter_has_subject BOOLEAN DEFAULT false,
  newsletter_has_cta BOOLEAN DEFAULT false,
  newsletter_sent_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for looking up adaptations by submission
CREATE INDEX idx_adapted_submission ON adapted_content (submission_id);

-- ============================================
-- UPDATED_AT TRIGGER
-- Auto-updates the updated_at column on submissions
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER submissions_updated_at
  BEFORE UPDATE ON submissions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

-- Enable RLS on both tables
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE adapted_content ENABLE ROW LEVEL SECURITY;

-- Policy: Allow anonymous read access (frontend uses anon key)
-- Submissions are readable by anyone with the anon key
CREATE POLICY "Allow public read on submissions"
  ON submissions FOR SELECT
  USING (true);

-- Policy: Allow insert from service role only (n8n uses service role key)
CREATE POLICY "Allow service role insert on submissions"
  ON submissions FOR INSERT
  WITH CHECK (true);  -- n8n authenticates with service role key which bypasses RLS

-- Policy: Allow update from service role only
CREATE POLICY "Allow service role update on submissions"
  ON submissions FOR UPDATE
  USING (true);

-- Adapted content: same pattern
CREATE POLICY "Allow public read on adapted_content"
  ON adapted_content FOR SELECT
  USING (true);

CREATE POLICY "Allow service role insert on adapted_content"
  ON adapted_content FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow service role update on adapted_content"
  ON adapted_content FOR UPDATE
  USING (true);

-- ============================================
-- VIEWS (convenience for frontend)
-- ============================================

-- Submission summary view for list display
CREATE OR REPLACE VIEW submission_summaries AS
SELECT
  s.id,
  s.input_type,
  s.raw_input,
  s.status,
  s.publish_immediately,
  s.selected_draft,
  s.created_at,
  s.updated_at,
  jsonb_array_length(s.drafts) as draft_count,
  -- Extract just titles and angles for list display (not full content)
  (
    SELECT jsonb_agg(
      jsonb_build_object(
        'index', d->>'index',
        'angle', d->>'angle',
        'title', d->>'title',
        'wordCount', d->>'wordCount'
      )
    )
    FROM jsonb_array_elements(s.drafts) AS d
  ) as draft_summaries,
  CASE WHEN ac.id IS NOT NULL THEN true ELSE false END as has_adapted_content,
  ac.linkedin_published_at IS NOT NULL as linkedin_published,
  ac.twitter_published_at IS NOT NULL as twitter_published,
  ac.newsletter_sent_at IS NOT NULL as newsletter_sent
FROM submissions s
LEFT JOIN adapted_content ac ON ac.submission_id = s.id
ORDER BY s.created_at DESC;
